### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by juddey** [bjonamu/ignite-react-app#1]
Hello! I am working on something very similar: https: github.com/juddey/ignite-kryptonite  You might like to take a look, feel free to ~steal stuff~ take insipiration.

Happy to have this closed, just wanted to say Hi! :smile:

**Comment by bjonamu** [comment]
This is epic. I am glad to see that I am not the only one who thinks that it would be great to have ignite for web apps. I am definitely going to ~steal stuff~ from your awesome repo. I also hope that we can collaborate on this idea.
